import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  OrganisationProfile,
  DomainAssessment,
  MaturityModel,
  Recommendation,
  DecisionAreaReadiness,
} from '../types';
import { getDecisionSupportLabel } from './scoring';
import { DomainNarrative } from './narrativeAnalysis';

const BRAND = {
  primary: [15, 50, 60] as [number, number, number],
  accent: [38, 120, 100] as [number, number, number],
  text: [30, 30, 30] as [number, number, number],
  muted: [120, 130, 135] as [number, number, number],
  bg: [247, 248, 249] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  high: [180, 60, 50] as [number, number, number],
  medium: [190, 140, 40] as [number, number, number],
  low: [60, 140, 100] as [number, number, number],
};

function addHeader(doc: jsPDF, title: string, y: number): number {
  doc.setFontSize(14);
  doc.setTextColor(...BRAND.primary);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 20, y);
  doc.setDrawColor(...BRAND.accent);
  doc.setLineWidth(0.5);
  doc.line(20, y + 2, 190, y + 2);
  return y + 10;
}

function checkPage(doc: jsPDF, y: number, needed: number = 30): number {
  if (y + needed > 270) {
    doc.addPage();
    return 20;
  }
  return y;
}

export function generatePDF(
  profile: OrganisationProfile,
  results: DomainAssessment[],
  model: MaturityModel,
  narratives: DomainNarrative[],
  recommendations: Recommendation[],
  decisionReadiness: DecisionAreaReadiness[],
  executiveSummary: {
    overallSummary: string;
    strongestDomains: string[];
    weakestDomains: string[];
    topGaps: string[];
    keyRisks: string[];
    headlineRecommendations: string[];
  }
) {
  const doc = new jsPDF();
  const domainMap = new Map(model.domains.map((d) => [d.id, d]));

  // --- Title Page ---
  doc.setFillColor(...BRAND.primary);
  doc.rect(0, 0, 210, 65, 'F');
  doc.setTextColor(...BRAND.white);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('GreenOps Data Input', 20, 30);
  doc.text('Maturity Assessment', 20, 42);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(profile.organisation_name, 20, 55);

  doc.setTextColor(...BRAND.text);
  let y = 80;
  doc.setFontSize(10);

  const profileFields = [
    ['Organisation', profile.organisation_name],
    ['Sector', profile.sector],
    ['Sub-sector', profile.sub_sector],
    ['Size', profile.organisation_size],
    ['Hosting profile', profile.hosting_profile],
    ['Assessment date', profile.assessment_date],
    ['Assessor', profile.assessor_name],
  ].filter(([, v]) => v);

  for (const [label, value] of profileFields) {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 65, y);
    y += 6;
  }

  if (profile.notes) {
    y += 4;
    doc.setFont('helvetica', 'bold');
    doc.text('Notes:', 20, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    const noteLines = doc.splitTextToSize(profile.notes, 160);
    doc.text(noteLines, 20, y);
    y += noteLines.length * 5;
  }

  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.muted);
  doc.text('Generated by Posetiv GreenOps Assessment Tool', 20, y);
  doc.text(`Report date: ${new Date().toISOString().split('T')[0]}`, 20, y + 5);

  // --- Executive Summary ---
  doc.addPage();
  y = 20;
  y = addHeader(doc, 'Executive Summary', y);
  doc.setFontSize(9);
  doc.setTextColor(...BRAND.text);
  doc.setFont('helvetica', 'normal');

  const summaryLines = doc.splitTextToSize(executiveSummary.overallSummary, 170);
  doc.text(summaryLines, 20, y);
  y += summaryLines.length * 4.5 + 6;

  // Strongest
  y = checkPage(doc, y, 20);
  doc.setFont('helvetica', 'bold');
  doc.text('Strongest domains:', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  for (const d of executiveSummary.strongestDomains) {
    doc.text(`• ${d}`, 24, y);
    y += 4.5;
  }

  y += 3;
  y = checkPage(doc, y, 20);
  doc.setFont('helvetica', 'bold');
  doc.text('Weakest domains:', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  for (const d of executiveSummary.weakestDomains) {
    doc.text(`• ${d}`, 24, y);
    y += 4.5;
  }

  if (executiveSummary.keyRisks.length > 0) {
    y += 3;
    y = checkPage(doc, y, 30);
    doc.setFont('helvetica', 'bold');
    doc.text('Key risks if unchanged:', 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    for (const r of executiveSummary.keyRisks) {
      const lines = doc.splitTextToSize(`• ${r}`, 166);
      y = checkPage(doc, y, lines.length * 4.5);
      doc.text(lines, 24, y);
      y += lines.length * 4.5 + 1;
    }
  }

  // --- Domain Score Table ---
  doc.addPage();
  y = 20;
  y = addHeader(doc, 'Domain Maturity Scores', y);

  const tableData = results.map((r) => {
    const domain = domainMap.get(r.domain_id);
    return [
      domain?.name || r.domain_id,
      String(r.maturity_score),
      String(r.impact_score),
      String(r.confidence_score),
      getDecisionSupportLabel(model, r.decision_support_status),
      r.priority || '-',
    ];
  });

  autoTable(doc, {
    startY: y,
    head: [['Domain', 'Maturity', 'Impact', 'Confidence', 'Decision Support', 'Priority']],
    body: tableData,
    theme: 'striped',
    styles: { fontSize: 7.5, cellPadding: 2 },
    headStyles: {
      fillColor: BRAND.primary,
      textColor: BRAND.white,
      fontStyle: 'bold',
    },
    columnStyles: {
      0: { cellWidth: 55 },
      1: { cellWidth: 18, halign: 'center' },
      2: { cellWidth: 16, halign: 'center' },
      3: { cellWidth: 22, halign: 'center' },
      4: { cellWidth: 42 },
      5: { cellWidth: 20, halign: 'center' },
    },
    margin: { left: 20, right: 20 },
  });

  // --- Domain Detail Sections ---
  for (const narrative of narratives) {
    doc.addPage();
    y = 20;
    y = addHeader(doc, narrative.domain_name, y);
    doc.setFontSize(9);

    // Current level
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND.primary);
    doc.text(narrative.currentLevel, 20, y);
    y += 5;

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...BRAND.text);
    const descLines = doc.splitTextToSize(narrative.currentLevelDescription, 170);
    doc.text(descLines, 20, y);
    y += descLines.length * 4.5 + 4;

    // Evidence
    y = checkPage(doc, y, 15);
    doc.setFont('helvetica', 'bold');
    doc.text('Evidence and rationale:', 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    const evidLines = doc.splitTextToSize(narrative.evidenceSummary, 170);
    doc.text(evidLines, 20, y);
    y += evidLines.length * 4.5 + 4;

    // Consequences
    y = checkPage(doc, y, 20);
    doc.setFont('helvetica', 'bold');
    doc.text('Operational consequences:', 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    const consLines = doc.splitTextToSize(narrative.consequences, 170);
    doc.text(consLines, 20, y);
    y += consLines.length * 4.5 + 4;

    // Supported decisions
    y = checkPage(doc, y, 15);
    doc.setFont('helvetica', 'bold');
    doc.text('Currently supports:', 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    for (const d of narrative.supportedDecisions) {
      doc.text(`• ${d}`, 24, y);
      y += 4.5;
    }

    y += 2;
    y = checkPage(doc, y, 15);
    doc.setFont('helvetica', 'bold');
    doc.text('Does not yet support:', 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    for (const d of narrative.unsupportedDecisions) {
      const lines = doc.splitTextToSize(`• ${d}`, 166);
      y = checkPage(doc, y, lines.length * 4.5);
      doc.text(lines, 24, y);
      y += lines.length * 4.5;
    }

    // Improvement
    y += 4;
    y = checkPage(doc, y, 20);
    doc.setFont('helvetica', 'bold');
    doc.text('Improvement actions:', 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    for (const a of narrative.improvementActions) {
      const lines = doc.splitTextToSize(`• ${a}`, 166);
      y = checkPage(doc, y, lines.length * 4.5);
      doc.text(lines, 24, y);
      y += lines.length * 4.5;
    }
  }

  // --- Decision Readiness ---
  doc.addPage();
  y = 20;
  y = addHeader(doc, 'GreenOps Decision Readiness', y);

  const drData = decisionReadiness.map((dr) => [
    dr.area,
    dr.label,
    dr.summary,
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Decision Area', 'Readiness', 'Assessment']],
    body: drData,
    theme: 'striped',
    styles: { fontSize: 7.5, cellPadding: 2 },
    headStyles: {
      fillColor: BRAND.primary,
      textColor: BRAND.white,
      fontStyle: 'bold',
    },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { cellWidth: 35 },
      2: { cellWidth: 90 },
    },
    margin: { left: 20, right: 20 },
  });

  // --- Recommendations ---
  doc.addPage();
  y = 20;
  y = addHeader(doc, 'Improvement Roadmap', y);

  const recData = recommendations.slice(0, 20).map((r) => [
    r.domain_name,
    r.action,
    r.priority,
    r.phase,
    r.benefit,
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Domain', 'Action', 'Priority', 'Phase', 'Expected Benefit']],
    body: recData,
    theme: 'striped',
    styles: { fontSize: 7, cellPadding: 2 },
    headStyles: {
      fillColor: BRAND.primary,
      textColor: BRAND.white,
      fontStyle: 'bold',
    },
    columnStyles: {
      0: { cellWidth: 35 },
      1: { cellWidth: 40 },
      2: { cellWidth: 18, halign: 'center' },
      3: { cellWidth: 25 },
      4: { cellWidth: 52 },
    },
    margin: { left: 20, right: 20 },
  });

  // Footer on each page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.muted);
    doc.text(
      `${profile.organisation_name} — GreenOps Data Maturity Assessment`,
      20,
      287
    );
    doc.text(`Page ${i} of ${pageCount}`, 175, 287);
  }

  return doc;
}

export function downloadPDF(
  profile: OrganisationProfile,
  results: DomainAssessment[],
  model: MaturityModel,
  narratives: DomainNarrative[],
  recommendations: Recommendation[],
  decisionReadiness: DecisionAreaReadiness[],
  executiveSummary: Parameters<typeof generatePDF>[6]
) {
  const doc = generatePDF(
    profile,
    results,
    model,
    narratives,
    recommendations,
    decisionReadiness,
    executiveSummary
  );
  const orgSlug = profile.organisation_name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+$/, '');
  doc.save(`greenops-maturity-${orgSlug}-${profile.assessment_date || 'assessment'}.pdf`);
}
